#!/usr/bin/perl

my $comments = <<'END_COMMENTS';
            <RURComments xml:space="preserve">
                <airSeal>&#x0D;&#x0A;Through the Canada Greener Homes Grant initiative, a grant between $550 and $1000 is available for improving the airtightness of your home based on the level achieved. This is one of the most cost-effective energy-saving measures you can undertake.  An air-sealing grant is available if the airtightness of your home is improved to achieve or exceed the air change rate target proposed above. Achieving any of the targets defined for your home typically requires that the work be performed by an air-sealing professional.</airSeal>
                <ceilings>The Canada Greener Homes Grant offers grants of up to $1,800 for increasing home insulation in attics, cathedral ceilings and flat roofs. The amount you are eligible for will depend on factors such as what insulation is currently in your home, how much insulation you add and type of attic/ceiling your home has. Insulation slows the rate of heat loss, resulting in improved energy use and can help save money. Installing insulation in an attic, cathedral ceiling or flat roof is eligible for a grant, as long as minimum levels of insulation and coverage are achieved. If your house consists of more than one roof or roof type, the grant amount will be pro-rated or calculated based on roof type and area.Please be aware that the Energy Advisor will have to have access to the attic at the time of the post retrofit appointment in order to take photos of the insulation and will require a copy of the invoice for the insulation.&#x0D;&#x0A;&#x0D;&#x0A;The insulation in your attic was assessed at R-31. Because the amount of insulation in your attic has been assessed as greater than R-25 but less than or equal to R-35, a grant of up to $250 is available through the Canada Greener Homes Grant initiative for adding insulation to reach R-50 or more</ceilings>
                <foundation>The Canada Greener Homes Grant initiative offers grants of up to $1500 for adding insulation to&#x0D;&#x0A;basement walls. Insulating basement walls can reduce energy costs and improve comfort.&#x0D;&#x0A;Grants are based on the RSI/R-value of the added insulation and the percentage of wall area&#x0D;&#x0A;insulated. The current amount of insulation does not affect the grant amounts. A minimum of&#x0D;&#x0A;20% of the exterior basement wall area must be insulated.</foundation>
                <HeatingSystem>Through the Canada Greener Homes Grant initiative, a grant of $2500 is available for smaller Air Source Heat Pumps (ASHP) or cold climate Air Source Heat Pumps (ccASHP). $5000 is available for large ccASHPs, depending upon the type installed. Speak with an HVAC professional for recommendations on the type of heat pump that is best suited for your home, for example, an air-source heat pump, or if you live in a colder climate, a cold-climate heat pump.&#x0D;&#x0A;Consult with an HVAC professional in this field to determine what type of system is practical and the right choice for your circumstances. To determine eligibility of the product you are seeking to purchase, confirm that it is included on the list of eligible equipment as found on the Canada Greener Homes Grant webpage.&#x0D;&#x0A;The heating load of your home is: 13.2kW. This value is provided as an approximation of the heating load of your home as it currently exists and any improvements you make to your home’s building envelope will affect this load. If you are going to share this value with your HVAC contractor make sure they are aware that they must do their own sizing calculations and that this value shouldn’t be relied upon to size a new heat pump. Your new heat pump must be sized to supply heat to your entire home. Ask the professional to size your heat pump according to the heating load of your entire home as indicated above, including any upgrades that have been performed to the building envelope.&#x0D;&#x0A;&#x0D;&#x0A;For more information: Natural Resources Canada has developed a package of materials related to air source heat pump sizing and selection, intended for use by mechanical system designers and renovation contractors. https://www.nrcan.gc.ca/maps-tools-and-publications/tools/modelling-tools/toolkit-for-air-source-heat-pump-sizing-and-selection/23558</HeatingSystem>
                <windows>Through the Canada Greener Homes Grant initiative, grants of either $125 or $250 per window rough opening are available when an ENERGY STAR certified or ENERGY STAR certified Most Efficient window is installed to replace an existing window. Replacing old, damaged or leaky windows with new ENERGY STAR certified products can help you save on energy, improve comfort and reduce noise. To determine eligibility of the product you are seeking to purchase, confirm that it is included on the list of eligible equipment as found on the Canada Greener Homes Grant webpage.&#x0D;&#x0A;Please have receipts and all Energy Star stickers available for the Energy Advisor at the post-retrofit appointment. Note that windows replaced without proof of Energy Star will not qualify for any rebate.</windows>
                <doors>Through the Canada Greener Homes Grant initiative, a grant of $125 per hinged door system is available when an eligible ENERGY STAR certified door or door system is installed. Replacing old, damaged or leaky hinged doors with new ENERGY STAR certified products can help you save on energy and improve comfort. To determine eligibility of the product you are seeking to purchase, confirm that it is included on the list of eligible equipment as found on the Canada Greener Homes Grant webpage.&#x0D;&#x0A;Please have receipts and all Energy Star stickers available for the Energy Advisor at the post-retrofit appointment. Note that doors replaced without proof of Energy Star will not qualify for any rebate.</doors>
                <VentilationSystem>Insufficient fresh air in your home can lead to condensation problems as well as indoor air quality issues. A Heat Recovery Ventilator provides fresh air to the home while simultaneously exhausting air to the exterior of the home with a heat exchanger at its core to improve efficiency. Using exhaust fans in your washrooms and kitchen may help with ventilation as well, however an HRV will provide balanced ventilation bringing in as much air as it removes and preheating (or precooling) air that enters the home.Please see the document titled "Heat Recovery Ventilator" that is linked in the report email for additional information.&#x0D;&#x0A;&#x0D;&#x0A;EfficiencyNS offers a $300 rebate for installing an HVI certified HRV.</VentilationSystem>
                <AdditionalComments>Through the Canada Greener Homes Grant, homeowners are eligible for up to $100 for the cost of pre-and post-retrofit EnerGuide evaluations, and up to $5,000 total for the implementation of eligible retrofits. Hiring a contractor is the recommended option in undertaking several of the home retrofits and for some retrofits it is a requirement. The contractor is responsible for complying with local bylaws and relevant provincial, territorial and federal legislation and guidelines.&#x0D;&#x0A;&#x0D;&#x0A;ELIGIBILITY INFORMATION&#x0D;&#x0A;For full details on eligibility requirements, eligible measures and grants for the recommended measures outlined below, please consult the Canada Greener Homes Grant website at:&#x0D;&#x0A;canada.ca/greener-homes-grant&#x0D;&#x0A;&#x0D;&#x0A;Many eligible retrofit measures under the Canada Greener Homes Grant have certain conditions for eligibility. These include:&#x0D;&#x0A;In order to be eligible for reimbursement of $100 of your evaluation fee, you must complete at least one retrofit that is both eligible and recommended by an energy advisor in this Renovation Upgrade Report&#x0D;&#x0A;If you wish to undertake resiliency measures or purchase a thermostat, you must also undertake another eligible energy efficiency measure in order to qualify for a grant.&#x0D;&#x0A;Purchased equipment such as heat pumps and windows must meet eligibility criteria and must be on the eligible product list as found on the Canada Greener Homes Grant website.&#x0D;&#x0A;All mechanical and electrical systems, with the exception of thermostats, must be installed by a licensed and trained professional*&#x0D;&#x0A;It is highly recommended that you use the attestation forms found on the Canada Greener Homes Grant website confirming that:&#x0D;&#x0A;- installation of an electrical or mechanical system has been completed by a trained and licensed professional*&#x0D;&#x0A;- an earth-energy (ground or water) system was installed in accordance with CSA standards&#x0D;&#x0A;- the heat pump has been sized to your entire home&#x0D;&#x0A;* When using a licensed professional it is highly recommended that you obtain proof of their licence to install equipment in your province or territory.&#x0D;&#x0A;All products must be purchased in Canada. Online purchases are only eligible if they are ordered from an online distributor located in Canada.&#x0D;&#x0A;</AdditionalComments>
            </RURComments>
END_COMMENTS

while ($line = <STDIN>) {
    if ($line =~ /RURComment/) {
        print ("$comments");
    } else {
        print ("$line");
    }
}

